name: Open production PR to master
on:
  push:
  pull_request_target:
    types: [closed]
    branches: [production]

jobs:
  open_prod_pr_to_master:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'production'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh -y
    - name: Create PR to master branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PROD_PR_BRANCH="${{ github.event.pull_request.head.ref }}"

        git fetch origin "${PROD_PR_BRANCH}":"${PROD_PR_BRANCH}"

        MASTER_PR_BRANCH="backmerge/${PROD_PR_BRANCH}"
        FORK_POINT="$(git rev-list --boundary origin/${PROD_PR_BRANCH}...origin/production | grep "^-" | cut -c2- | tail -1)"

        echo "revlist : $(git rev-list --boundary origin/${PROD_PR_BRANCH}...origin/production)"
        echo "orkpointL : $FORK_POINT"

        git checkout -b "${MASTER_PR_BRANCH}" "${FORK_POINT}"
        git push origin "${MASTER_PR_BRANCH}"

        AUTHOR="${{ github.event.pull_request.user.login }}"

        {
          echo "$(jq -r .pull_request.body "${GITHUB_EVENT_PATH}")"
          echo
          echo
          echo "_Production PR: #${{ github.event.pull_request.number }} @ @${AUTHOR}_"
        } > body.txt

        gh pr create \
          --repo "${{ github.repository }}" \
          --head "${MASTER_PR_BRANCH}" \
          --base "master" \
          --title "[master] ${{ github.event.pull_request.title }}" \
          --body-file body.txt \
          --assignee "${AUTHOR}" \
          --label "master"
